import type { AuditResult } from './types'

function formatCurrency(value: number): string {
  return `$${Math.round(value).toLocaleString()}`
}

function lineText(text: string, maxLength = 86): string[] {
  const words = text.split(' ')
  const lines: string[] = []
  let currentLine = ''

  for (const word of words) {
    const nextLine = currentLine ? `${currentLine} ${word}` : word

    if (nextLine.length > maxLength) {
      lines.push(currentLine)
      currentLine = word
    } else {
      currentLine = nextLine
    }
  }

  if (currentLine) {
    lines.push(currentLine)
  }

  return lines
}

export async function exportAuditPDF(auditResult: AuditResult): Promise<void> {
  const { jsPDF } = await import('jspdf')
  const pdf = new jsPDF()
  const pageHeight = pdf.internal.pageSize.getHeight()
  const marginX = 16
  let y = 18

  function ensureSpace(requiredHeight: number) {
    if (y + requiredHeight <= pageHeight - 20) {
      return
    }

    pdf.addPage()
    y = 18
  }

  function addWrappedText(text: string, options?: { fontSize?: number; lineHeight?: number }) {
    const fontSize = options?.fontSize ?? 10
    const lineHeight = options?.lineHeight ?? 6
    const lines = lineText(text)

    pdf.setFontSize(fontSize)
    for (const line of lines) {
      ensureSpace(lineHeight)
      pdf.text(line, marginX, y)
      y += lineHeight
    }
  }

  const generatedDate = new Intl.DateTimeFormat('en-US', {
    dateStyle: 'medium',
    timeStyle: 'short',
  }).format(new Date())
  const burnScore = auditResult.burnScore ?? 100

  pdf.setFont('helvetica', 'bold')
  pdf.setFontSize(18)
  pdf.text('BurnLens AI Spend Audit', marginX, y)
  y += 8

  pdf.setFont('helvetica', 'normal')
  pdf.setFontSize(10)
  pdf.text(`Date generated: ${generatedDate}`, marginX, y)
  y += 10

  pdf.setFont('helvetica', 'bold')
  addWrappedText(
    `Total monthly savings potential: ${formatCurrency(auditResult.monthlySavings)}/mo (${formatCurrency(auditResult.annualSavings)}/yr)`,
    { fontSize: 12, lineHeight: 7 },
  )
  y += 2

  pdf.setFont('helvetica', 'bold')
  pdf.text(`BurnLens Score: ${burnScore}/100`, marginX, y)
  y += 10

  pdf.setFontSize(14)
  pdf.text('Per-tool recommendations', marginX, y)
  y += 8

  for (const recommendation of auditResult.recommendations) {
    ensureSpace(32)
    pdf.setFont('helvetica', 'bold')
    pdf.setFontSize(11)
    pdf.text(recommendation.toolName, marginX, y)
    y += 6

    pdf.setFont('helvetica', 'normal')
    addWrappedText(`Current plan: ${recommendation.currentPlan}`)
    addWrappedText(`Current spend: ${formatCurrency(recommendation.currentSpend)}/mo`)
    addWrappedText(`Recommendation: ${recommendation.recommendedAction}`)
    addWrappedText(`Monthly savings: ${formatCurrency(recommendation.monthlySaving)}/mo`)
    y += 4
  }

  ensureSpace(14)
  pdf.setFont('helvetica', 'normal')
  pdf.setFontSize(9)
  pdf.text(
    'Generated by BurnLens - burnlens.vercel.app | Discounted AI credits at credex.rocks',
    marginX,
    pageHeight - 12,
  )

  pdf.save('burnlens-ai-spend-audit.pdf')
}
